### ISSUE TITLE
Correcciones QMP - Primera iteración

### ISSUE THREAD

**Issue by PalumboN** [gabycosta04/QMP#1]
Hola @gabycosta04 , te dejo algunos comentarios de la primera entrega de QMP.

En términos generales está bien aunque me hubiera gustado una explicación general de cómo se resuelve cada requerimiento en prosa. Como también justificaciones de algunas decisiones que ahora me dejan en dudas (como el nombre "PrendaBuilder")

Por otro lado el diagrama tiene algunas flechas mal:
- El Tipo conoce a una Categoría (no usa). PrendaBuilder la usaría en todo caso, que no la conoce directamente. 
- Y con el color, como la flecha de asociación (conoce) es más fuerte que la de "usa", con marcar la primera basta, total es medio obvio que si conoce a otro objeto es porque lo usa en algún momento.

Eso respecto a la comunicación. Ahora respecto a tu solución:
- Lo primero para destacar es que tu PrendaBuilder en realidad no es un _Builder_. Un `PrendaBuilder` sería un objeto que sabe construir Prendas. En tu caso, el objeto que declaraste **es una Prenda**.
- Sobre el modelado de las características me parecen bien. Hiciste un cambio en el modelo de Color: cualquiera de las dos alternativas eran válidas, lo importante es cómo **justificar** cada una (por eso te recomiendo agregar prosa que explique / justifique las decisiones de tu solución).
- Las validaciones de nullables en la prenda que lanzan excepción están muy bien. Hacés lo mismo para los Tipos (que tienen un nombre _muy_ genérico, yo le pondría `TipoPrenda` o algo así), que puede ser un poco innecesario: si son enums, vos vas a declarar todos los tipos, y ahí tenés mayor control de cómo se instancian.
- Con al categoría pasa algo que no cierra: La prenda recibe una categoría por constructor pero no hace nada con ella más que validar por null. Después cuando se le pregunta devuelve el que tiene su tipo. En este esquema no es necesario entonces aclarar la categoría al instanciar una prenda, con solo decir su tipo es suficiente.
- Por último, respecto al color secundario opcional: ahora solamente se puede indicar a través del setter `indicarColorSecundario` (si estamos en java este método debería llamarse `setColorSecundario`, siguiendo las convenciones del lenguaje). Hay que tener cuidado con esta decisión porque eso haría que el objeto pueda mutar dicha propiedad en cualquier momento, que es algo que no pasa con el resto de los atributos (y tiene sentido que no queramos eso, ya que se está haciendo una validación al construirse, y no queremos cambiar esos valores). Así que hay que tener cuidado con la _mutabilidad_ o _inmutabilidad_ de los objetos (es una decisión a tomar). Si no se quisiera hacer mutable se podría recibir por constructor (mandando null en el caso que no tenga), o teniendo otro constructor que llame al primero.

**Comment by gabycosta04** [comment]
Ahhhhh perefecto, gracias por las correcciones
