### ISSUE TITLE
Comentarios QMP - Segunda entrega

### ISSUE THREAD

**Issue by PalumboN** [gabycosta04/QMP#2]
Hola @gabycosta04 , te dejo algunos comentarios de la segunda entrega de QMP del viernes pasado, disculpá la demora.

En términos generales la comunicación del diseño está bien. Estaría bueno, aprovechando que enumeraste los requerimientos en el README, aclarar qué se pensó para resolver cada uno (o algunos relacionados), como documentación que complementa el diagrama (que permite tener una idea global de las relaciones entre entidades) y el pseudocódigo (que sirve más para aclarar cierta lógica puntual).

Respecto a la solución planteada:

- Faltaría resolver el requerimiento de tener prendas con tipo y materiales consistentes (faltaron pensar asociaciones para poder hacer esa validación):
> evitar elegir materiales inconsistentes con el tipo de prenda

- Me gustó este comentario:
https://github.com/gabycosta04/QMP/blob/49c24109a622e2771c7bc301287508696f523a4d/src/main/java/SegundaIteracion/Borrador.java#L7-L8
que justifica el por qué tener un borrador :+1: 

Venís bien, seguí así!

------

Un comentario aparte, fuiste el único de tu grupo que entregó esta iteración. Recuerden que estos ejercicios son individuales y sirven como práctica para el parcial. La idea es corregir individualmente a alguien distinto cada vez, ya te había corregido a vos la vez pasada así que en esta le quería corregir a otra persona del grupo pero no entregaron. Si bien con que entregue un integrante del grupo se cumple con lo pedido, lo ideal sería o que esa persona vaya rotando, o que lo entregue más de uno, así todes tienen una práctica con feedback antes del parcial.

Lo aviso por si quedaron dudas sobre estos ejercicios (de carácter individual y feedback personalizado). Por cualquier duda dejo [este link](https://dds-jv.github.io/pautas/sobre-los-trabajos-practicos).

**Comment by gabycosta04** [comment]
Hola nahue, gracias por todos los comentarios. Perdon que recien los leo, desde ya muchas gracias por todo y me quedo claro, me sirve un monton!!
